export const LOAD_YEAR = "LOAD_YEAR";
export const LOAD_YEAR_SUCCESS = "LOAD_YEAR_SUCCESS";
export const LOAD_YEAR_ERROR = "LOAD_YEAR_ERROR";

export const LOAD_BUDGETS = "LOAD_BUDGETS";
export const LOAD_BUDGETS_SUCCESS = "LOAD_BUDGETS_SUCCESS";
export const LOAD_BUDGETS_ERROR = "LOAD_BUDGETS_ERROR";

export const POST_BUDGETS = "POST_BUDGETS";
export const POST_BUDGETS_SUCCESS = "POST_BUDGETS_SUCCESS";
export const POST_BUDGETS_ERROR = "POST_BUDGETS_ERROR";

export const PUT_BUDGETS = "PUT_BUDGETS";
export const PUT_BUDGETS_SUCCESS = "PUT_BUDGETS_SUCCESS";
export const PUT_BUDGETS_ERROR = "PUT_BUDGETS_ERROR";
